CREATE TABLE notification_preferences (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  campaign_updates BOOLEAN NOT NULL DEFAULT TRUE,
  refunds BOOLEAN NOT NULL DEFAULT TRUE,
  disputes BOOLEAN NOT NULL DEFAULT TRUE,
  milestones BOOLEAN NOT NULL DEFAULT TRUE,
  marketing BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
